name: test cicd

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name : Checkout
        uses : actions/checkout@v5.0.0

      - name : SetUp JDK
        uses : actions/setup-java@v5.0.0
        with:
          java-version : '21'
          distribution: 'temurin'

      - name : Grant Permission
        run : chmod +x ./gradlew

      - name : build with gradle
        run: ./gradlew bootJar -x test

      - name: Transfer Build Files to EC2
        uses: appleboy/scp-action@master
        with :
          host: ${{ secrets.PRIVATE_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{secrets.USER }}
          proxy_key: ${{ secrets.KEY }}
          source: build/libs/myce-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/app

      - name : deploy test with github actions
        uses : appleboy/ssh-action@v0.1.6
        with :
          host: ${{ secrets.PRIVATE_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{secrets.USER }}
          proxy_key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/app
            
            ENV_FILE=/home/ec2-user/app/.env
            JAR_PATH=/home/ec2-user/app/myapp.jar
            LOG_PATH=/home/ec2-user/app/app.log
      
            export $(grep -v '^#' "$ENV_FILE" | xargs)
            
            PID=$(pgrep -f $JAR_PATH)
            if [ -n "$PID" ]; then
            echo "> Stopping existing process ($PID)..."
            kill -9 $PID
            sleep 2
            fi
            
            nohup java -jar $JAR_PATH --spring.profiles.active=prod > $LOG_PATH 2>&1 &
            
            NEW_PID=$!
            
            if ps -p $NEW_PID > /dev/null 2>&1; then
            echo "Application started successfully!"
            echo "PID: ${NEW_PID}"
            else
            echo "Failed to start application."
            fi

            
            
            

