name: test cicd

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name : Checkout
        uses : actions/checkout@v5.0.0

      - name : SetUp JDK
        uses : actions/setup-java@v5.0.0
        with:
          java-version : '21'
          distribution: 'temurin'

      - name : Grant Permission
        run : chmod +x ./gradlew

      - name : build with gradle
        run: ./gradlew bootJar -x test

      - name: Transfer Build Files to EC2
        uses: appleboy/scp-action@master
        with :
          host: ${{ secrets.PRIVATE_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{secrets.USER }}
          proxy_key: ${{ secrets.KEY }}
          source: "build/libs/myce-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app"
          strip_components: 2

      - name : deploy test with github actions
        uses : appleboy/ssh-action@v0.1.6
        with :
          host: ${{ secrets.PRIVATE_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ secrets.HOST }}
          proxy_username: ${{secrets.USER }}
          proxy_key: ${{ secrets.KEY }}
          script: |
            cd /home/ec2-user/app
            ./start.sh
            
            
            

